//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sjsu.mobiletaas.resourcemanager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int Userid { get; set; }
        public string EmulatorId { get; set; }
        public string TaskId { get; set; }
        public int Version { get; set; }
        public int Memory { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public bool Billed { get; set; }
        public decimal Rate { get; set; }
    
        public virtual User User { get; set; }
    }
}
